### ISSUE TITLE
How to simulate changes in the "matches" property?

### ISSUE THREAD

**Issue by timrobinson33** [dyakovk/jest-matchmedia-mock#3]
Sorry I'm not sure if this is a deficiency in the component or just I don't understand how to use it.

In my application I have a number of media queries, each query has a listener, and the listener is fired when the "matches" property changes from true to false or vice versa. What I want to simulate is any specific media query changing from matched to not matched, so I want my test to do something like this:

```js
const mediaQuery1 = '(prefers-color-scheme: light)';
const mediaQuery2 = '(min-width: 640px)';
const listener1 = jest.fn();
const listener2 = jest.fn();
const mql1 = window.matchMedia(mediaQuery1);
const mql2 = window.matchMedia(mediaQuery2);
mql1.addListener(listener1);
mql2.addListener(listener2);

matchMedia.useMediaQuery(mediaQuery1, true);
matchMedia.useMediaQuery(mediaQuery2, true);
expect(listener1).toBeCalledTimes(1);
expect(listener2).toBeCalledTimes(1);
listener1.mockReset();
listener2.mockReset();
matchMedia.useMediaQuery(mediaQuery2, false);
expect(listener1).toBeCalledTimes(0);
expect(listener2).toBeCalledTimes(1);
```

However, it seems that jest-matchmedia-mock has the concept of "current media query" which is the only one that's matched. When I call useMediaQuery() to change the current query, listeners attached to other media queries are not fired. Is there any way to achieve the above result?

**Comment by dyakovk** [comment]
We can't break the normal behavior of that how `window.matchMedia` works. And, of course, it's wrong to reassign the `matches` boolean property that is the part of received MediaQueryList event. Think of `useMediaQuery` as if some media-query has become active at the current moment. We simulate some user action like that. For example, the window width of the browser window has changed (call `useMediaQuery`), and now we need to call all the listeners that subscribe to this event.

I don't have any other ideas how to implement event-driven behavior of the `window.matchMedia`. After all, writing unit tests is all about testing a piece or pieces of functionality of a single module. If you are testing multiple media queries at once, you most likely need to refactor your tests.
